kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: InvokeAzureAgent
      id: invoice-validation-agent
      agent:
        name: invoice-validation-agent
      input:
        messages: =System.LastMessage
      output:
        autoSend: true
        messages: Local.LastMessage
    - kind: ConditionGroup
      conditions:
        - condition: =!IsBlank(Find("<INV_OK>", Last(Local.LastMessage).Text))
          actions:
            - kind: Question
              variable: Local.UserApproval
              id: action-1764937921178
              entity: StringPrebuiltEntity
              skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
              prompt: <QUESTION>Validation OK - Approve?
            - kind: SendActivity
              activity: <FINAL> Success! Ivoice approved for payment processing.
              id: action-1764942712798
          id: if-action-1764883723763-0
      id: action-1764883723763
      elseActions:
        - kind: Question
          variable: Local.UserApproval
          id: action-1764937921111
          entity: StringPrebuiltEntity
          skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
          prompt: <QUESTION>Validation Fail - send back?
        - kind: InvokeAzureAgent
          id: invoice-mailer-agent
          agent:
            name: invoice-mailer-agent
          input:
            messages: =Local.LastMessage
          output:
            autoSend: true
        - kind: SendActivity
          activity: <FINAL> Invoice sent back to supplier.
          id: action-1764963963215
    - kind: EndConversation
      id: action-1764936956468
id: ""
name: wf2
description: ""
