kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: InvokeAzureAgent
      id: invoice-validation-agent
      agent:
        name: invoice-validation-agent
      input:
        messages: =System.LastMessage
      output:
        autoSend: true
        messages: Local.LastMessage
        responseObject: Local.LastMessageJSON
    - kind: ConditionGroup
      conditions:
        - condition: =!IsBlank(Find("<INV_OK>", Last(Local.LastMessage).Text))
          actions:
            - kind: InvokeAzureAgent
              id: invoice-validation-summary
              agent:
                name: invoice-validation-summary-agent
              input:
                messages: =Last(Local.LastMessage).Text
              output:
                autoSend: true
                messages: Local.ValSummary
            - kind: Question
              variable: Local.UserApproval
              id: action-1764937921178
              entity: StringPrebuiltEntity
              skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
              prompt: <QUESTION>Invoice validation passed. {Last(Local.ValSummary).Text} Approve?
            - kind: InvokeAzureAgent
              id: invoice-process-summary-agent
              agent:
                name: invoice-process-summary-agent
              input:
                messages: =Local.LastMessage
              output:
                autoSend: true
                messages: Local.LastMessage
            - kind: SendActivity
              activity: <FINAL> Success! {Last(Local.LastMessage).Text}
              id: action-1764942712798
          id: if-action-1764883723763-0
      id: action-1764883723763
      elseActions:
        - kind: InvokeAzureAgent
          id: invoice-validation-summary-agent
          agent:
            name: invoice-validation-summary-agent
          input:
            messages: =Last(Local.LastMessage).Text
          output:
            autoSend: true
            messages: Local.ValSummary
        - kind: Question
          variable: Local.UserApproval
          id: action-1764937921111
          entity: StringPrebuiltEntity
          skipQuestionMode: SkipOnFirstExecutionIfVariableHasValue
          prompt: "<QUESTION>Invoice validation failed: {Last(Local.ValSummary).Text} - Revoke?"
        - kind: InvokeAzureAgent
          id: invoice-mailer-agent
          agent:
            name: invoice-mailer-agent
          input:
            messages: =Local.LastMessage
          output:
            autoSend: true
        - kind: SendActivity
          activity: <FINAL> Invoice revoked.
          id: action-1764963963215
    - kind: EndConversation
      id: action-1764936956468
id: ""
name: Cofilot-Invoice-Processing-Demo
description: ""
